[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
python_paths = [
    ".",
    "src"
]
addopts = [
    "--strict-markers",
    "--strict-config",
    "--verbose",
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests",
]